import type { AgentConfig } from '@axplane/agents';
import type { RunAgentFn } from '@axplane/eval';
import { executeEvalRun } from '@axplane/eval';
import type { LabRepository } from '@axplane/lab';
import { executeOptimizationWorkflow } from '@axplane/lab';
import type { OptimizerType } from '@axplane/lab';
import type { ForgeEvalCaseDraft } from './eval-seed';
import type { ForgeIntake, PartialForgeIntake } from './intake-schema';
import { mergeForgeIntake, validateIntakeForScaffold } from './intake-schema';
import type { ForgeDraftMeta, ForgeScaffoldMode, ForgeScaffoldStrategy } from './llm-scaffold';
import { buildForgeDraftWithStrategy } from './llm-scaffold';
import { slugifyAgentId } from './scaffold';

export type ForgeDraft = {
  agentConfig: AgentConfig;
  evalCases: ForgeEvalCaseDraft[];
};

export type ForgeSessionRecord = {
  id: string;
  status: string;
  intakeJson: PartialForgeIntake;
  draftJson: ForgeDraft | null;
  draftMetaJson: ForgeDraftMeta | null;
  agentId: string | null;
  suiteId: string | null;
  error: string | null;
};

export type ForgeRepository = {
  getForgeSession(id: string): Promise<ForgeSessionRecord | null>;
  updateForgeSession(
    id: string,
    patch: {
      status?: string;
      intakeJson?: PartialForgeIntake;
      draftJson?: ForgeDraft | null;
      draftMetaJson?: ForgeDraftMeta | null;
      agentId?: string | null;
      suiteId?: string | null;
      error?: string | null;
    },
  ): Promise<ForgeSessionRecord | null>;
  createAgent(input: {
    id: string;
    name: string;
    description?: string;
    signature: string;
    configJson: unknown;
  }): Promise<unknown>;
  createEvalSuite(input: {
    name: string;
    description?: string;
    agentId?: string | null;
    cases: Array<{ name: string; taskText: string; criteria: unknown[]; sortOrder?: number }>;
  }): Promise<{ id: string } | null>;
};

export type BuildForgeDraftInput = {
  intake: PartialForgeIntake;
  agentId?: string;
  name?: string;
  strategy?: ForgeScaffoldStrategy;
  mode?: ForgeScaffoldMode;
};

export async function buildForgeDraft(input: BuildForgeDraftInput): Promise<{
  draft: ForgeDraft;
  meta: ForgeDraftMeta;
}> {
  const intake = validateIntakeForScaffold(input.intake);
  const name = input.name ?? intake.task.slice(0, 64);
  const agentId = input.agentId ?? slugifyAgentId(name);
  const { draft, meta } = await buildForgeDraftWithStrategy({
    intake,
    agentId,
    name,
    strategy: input.strategy,
    mode: input.mode,
  });
  return { draft, meta };
}

export type ScaffoldForgeSessionArgs = {
  repo: ForgeRepository;
  sessionId: string;
  agentId?: string;
  name?: string;
  strategy?: ForgeScaffoldStrategy;
  mode?: ForgeScaffoldMode;
};

export async function scaffoldForgeSession(
  args: ScaffoldForgeSessionArgs,
): Promise<{ draft: ForgeDraft; meta: ForgeDraftMeta }> {
  const session = await args.repo.getForgeSession(args.sessionId);
  if (!session) throw new Error(`Forge session not found: ${args.sessionId}`);

  const intake = mergeForgeIntake(session.intakeJson ?? {}, {});
  const { draft, meta } = await buildForgeDraft({
    intake,
    agentId: args.agentId,
    name: args.name,
    strategy: args.strategy,
    mode: args.mode,
  });

  await args.repo.updateForgeSession(args.sessionId, {
    status: 'scaffolded',
    draftJson: draft,
    draftMetaJson: meta,
    error: null,
  });

  return { draft, meta };
}

export type CommitForgeSessionArgs = {
  repo: ForgeRepository;
  sessionId: string;
  agentId?: string;
  name?: string;
  runBaseline?: boolean;
  mode?: 'mock' | 'real';
  runAgent?: RunAgentFn;
  parseAgentConfig?: (json: unknown) => AgentConfig;
};

export type CommitForgeSessionResult = {
  agentId: string;
  suiteId: string;
  baselineEvalRunId?: string;
};

export async function commitForgeSession(
  args: CommitForgeSessionArgs,
): Promise<CommitForgeSessionResult> {
  const session = await args.repo.getForgeSession(args.sessionId);
  if (!session) throw new Error(`Forge session not found: ${args.sessionId}`);

  let draft = session.draftJson;
  if (!draft) {
    const scaffolded = await scaffoldForgeSession({
      repo: args.repo,
      sessionId: args.sessionId,
      agentId: args.agentId,
      name: args.name,
    });
    draft = scaffolded.draft;
  }

  const agentId = args.agentId ?? draft.agentConfig.id;
  const name = args.name ?? draft.agentConfig.name;
  const config = { ...draft.agentConfig, id: agentId, name };

  try {
    await args.repo.createAgent({
      id: agentId,
      name,
      description: config.description,
      signature: config.signature,
      configJson: config,
    });

    const suite = await args.repo.createEvalSuite({
      name: `${name} — Forge eval`,
      description: `Eval suite generated by Agent Forge for ${agentId}`,
      agentId,
      cases: draft.evalCases.map((row) => ({
        name: row.name,
        taskText: row.taskText,
        criteria: row.criteria,
        sortOrder: row.sortOrder,
      })),
    });

    if (!suite?.id) {
      throw new Error('Failed to create eval suite');
    }

    await args.repo.updateForgeSession(args.sessionId, {
      status: 'committed',
      agentId,
      suiteId: suite.id,
      error: null,
    });

    let baselineEvalRunId: string | undefined;
    if (args.runBaseline && args.runAgent && args.parseAgentConfig) {
      const baseline = await runForgeBaseline({
        repo: args.repo as ForgeRepository & LabRepository,
        sessionId: args.sessionId,
        mode: args.mode ?? 'mock',
        runAgent: args.runAgent,
        parseAgentConfig: args.parseAgentConfig,
      });
      baselineEvalRunId = baseline.evalRunId;
    }

    return { agentId, suiteId: suite.id, baselineEvalRunId };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await args.repo.updateForgeSession(args.sessionId, {
      status: 'failed',
      error: message,
    });
    throw error;
  }
}

export type RunForgeBaselineArgs = {
  repo: ForgeRepository & LabRepository;
  sessionId: string;
  mode?: 'mock' | 'real';
  runAgent: RunAgentFn;
  parseAgentConfig: (json: unknown) => AgentConfig;
};

export async function runForgeBaseline(args: RunForgeBaselineArgs) {
  const session = await args.repo.getForgeSession(args.sessionId);
  if (!session?.agentId || !session.suiteId) {
    throw new Error('Forge session must be committed before baseline eval');
  }

  return executeEvalRun({
    repo: args.repo,
    suiteId: session.suiteId,
    agentId: session.agentId,
    runLabel: 'baseline',
    mode: args.mode ?? 'mock',
    runAgent: args.runAgent,
    parseAgentConfig: args.parseAgentConfig,
  });
}

export type RunForgeOptimizeArgs = {
  repo: ForgeRepository & LabRepository;
  sessionId: string;
  optimizerType?: OptimizerType;
  optimizerConfig?: Record<string, unknown>;
  mode?: 'mock' | 'real';
  runAgent: RunAgentFn;
  parseAgentConfig: (json: unknown) => AgentConfig;
  loadAgentConfig: (agentId: string) => Promise<AgentConfig>;
};

export async function runForgeOptimize(args: RunForgeOptimizeArgs) {
  const session = await args.repo.getForgeSession(args.sessionId);
  if (!session?.agentId || !session.suiteId) {
    throw new Error('Forge session must be committed before optimize');
  }

  const agentConfig = await args.loadAgentConfig(session.agentId);
  if (args.optimizerType === 'ax-native' && agentConfig.mode !== 'rlm') {
    throw new Error('ax-native optimizer requires agent mode "rlm"; use ax-native-mock or set optimizeRequested at intake');
  }

  await args.repo.updateForgeSession(args.sessionId, {
    status: 'optimizing',
    error: null,
  });

  try {
    const result = await executeOptimizationWorkflow({
      repo: args.repo,
      agentId: session.agentId,
      suiteId: session.suiteId,
      optimizerType: args.optimizerType ?? 'ax-native-mock',
      optimizerConfig: args.optimizerConfig,
      mode: args.mode ?? 'mock',
      runAgent: args.runAgent,
      parseAgentConfig: args.parseAgentConfig,
      loadAgentConfig: args.loadAgentConfig,
    });

    await args.repo.updateForgeSession(args.sessionId, {
      status: 'done',
      error: null,
    });

    return result;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    await args.repo.updateForgeSession(args.sessionId, {
      status: 'failed',
      error: message,
    });
    throw error;
  }
}

export type { ForgeIntake, PartialForgeIntake, ForgeEvalCaseDraft };
